### ISSUE TITLE
Melpa recipe

### ISSUE THREAD

**Issue by leungbk** [seanfarley/mu4e-patch#3]
It would be nice if this package were available on Melpa.

**Comment by seanfarley** [comment]
Ah, yes, I almost forgot about this not being on melpa! Thanks for the poke; I'll try to whip up something this weekend.

**Comment by husainaloos** [comment]
Any update on this? I wonder if this is still something you want to do.

**Comment by seanfarley** [comment]
Finally got around to [doing this](https://github.com/melpa/melpa/pull/7711) (along with updating for the new gnus view). Once I get the approval from melpa, I'll update the readme and close this issue.
