### ISSUE TITLE
Hooking into mu4e-view-mode-hook no longer works

### ISSUE THREAD

**Issue by stsquad** [seanfarley/mu4e-patch#4]
I don't know if this is a result of the gnus-article-mode re-write but any changes made by mu4e-patch-highlight get squashed by something updating the buffer before the final display.

**Comment by stsquad** [comment]
So I've worked around the problem with an idle timer for now:

    (defun my-defer-mu4e-patch-highlight ()
      "Set-up to highlight patch once we are idle."
      (run-with-idle-timer
         0.1 nil
         (lambda (buffer)
           (with-current-buffer buffer
             (mu4e-patch-highlight))) (current-buffer)))

    (use-package mu4e-patch
      :load-path (lambda () (my-return-path-if-ok
                             "~/src/emacs/mu4e-patch.git"))
      :config (add-hook 'mu4e-view-mode-hook #'my-defer-mu4e-patch-highlight))

**Comment by seanfarley** [comment]
Yeah, this is due to `gnus-article-mode` being the new default. The good news is that `gnus-article-mode` makes this package obsolete since it was forked from gnus-patch to being with. I use this for now:

https://github.com/seanfarley/dotfiles/blob/main/doom/%2Bgnus-patch.el

**Comment by stsquad** [comment]
Has anything been packaged up or up-streamed for this?

**Comment by seanfarley** [comment]
Not that I know of. I don't think anything is preventing, say, someone like yourself, from adding it to melpa as long as your willing to more-or-less take care of maintaining it (which might mean updating the code to modern elisp and whatnot). I'm trying to minimize the number of packages I maintain, so I'm hoping someone else can step up to package it 😬

**Comment by seanfarley** [comment]
I've updated the package to include support for `gnus` and also instructions on the hooks to modify. This should just work now if you follow the updated instructions in the readme. Thanks for reporting!
